version: '2'
services:

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest

  application:
    build: 
      context: .
    image: "socialsirius/tmtm:${VERSION}"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_HOST=db
    depends_on:
      - db
      - redis
