# Generated by Django 2.2 on 2020-10-08 21:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20201008_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='my_endpoint',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
