# Generated by Django 2.2 on 2020-10-08 22:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_qrcode_my_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairwiseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=64)),
                ('their_did', models.CharField(db_index=True, max_length=64)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
