# Generated by Django 2.2 on 2020-10-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_authref'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialQR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=126)),
                ('connection_key', models.CharField(max_length=128)),
                ('qr_url', models.CharField(max_length=2048)),
            ],
        ),
    ]
