# Generated by Django 2.2 on 2020-10-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_credentialqr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialqr',
            name='connection_key',
        ),
        migrations.RemoveField(
            model_name='credentialqr',
            name='qr_url',
        ),
        migrations.AddField(
            model_name='credentialqr',
            name='qr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.QRCode'),
        ),
    ]
