# Generated by Django 2.2 on 2020-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='entity',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seq_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('entity', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('seq_no', 'ledger')},
        ),
    ]
