# Generated by Django 2.2 on 2020-09-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0005_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='private_uid',
        ),
    ]
