# Generated by Django 2.2 on 2020-09-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0006_remove_content_private_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='md5',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
