# Generated by Django 2.2 on 2020-09-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0007_content_md5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='owner',
            new_name='entity',
        ),
    ]
