# Generated by Django 2.2 on 2020-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0008_auto_20200918_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
