# Generated by Django 2.2 on 2020-10-11 23:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0012_auto_20200923_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='GURecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(db_index=True, max_length=36)),
                ('no', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('cargo_name', models.CharField(max_length=128)),
                ('depart_station', models.CharField(max_length=128)),
                ('arrival_station', models.CharField(max_length=128)),
                ('month', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=128)),
                ('decade', models.CharField(max_length=128)),
                ('tonnage', models.CharField(max_length=128)),
                ('shipper', models.CharField(max_length=128)),
                ('attachments', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
