# Generated by Django 2.2 on 2021-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0014_transaction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='actor_entity',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
