"""
Django settings for project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import logging
import sirius_sdk


logging.getLogger().setLevel(logging.WARNING)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7ns7(xo2h^f*%6_a#tdt_toh9$82p(+a1y_f!nref=i3my8@rw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'scripts',
    'wrapper',
    'ui'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'
ASGI_APPLICATION = 'settings.routing.application'


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'wrapper.authentication.ExtendedBasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME') or 'postgres',
        'USER': os.environ.get('DATABASE_USER') or 'postgres',
        'PASSWORD': os.environ.get('DATABASE_PASSWORD') or 'postgres',
        'HOST': os.environ.get('DATABASE_HOST') or 'db',
        'PORT': os.environ.get('DATABASE_PORT') or 5432,
        'TEST': {
            'NAME': 'test_database',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/content/'
MEDIA_ROOT = '/tmp'

SENTRY_DSN = os.getenv('SENTRY_DSN')

AGENT = {
    'credentials': os.getenv('AGENT_CREDENTIALS'),
    'server_address': os.getenv('AGENT_SERVER_ADDRESS'),
    'entity': os.getenv('AGENT_ENTITY'),
    'my_verkey': os.getenv('AGENT_MY_VERKEY'),
    'my_secret_key': os.getenv('AGENT_MY_SECRET_KEY'),
    'agent_verkey': os.getenv('AGENT_VERKEY'),
    'is_sea': os.getenv('AGENT_IS_SEA', False) in ['1', 'on', 'yes'],
    'ledger': 'staging'
}
if AGENT['credentials'] and AGENT['server_address']:
    sirius_sdk.init(
        server_uri=AGENT['server_address'],
        credentials=AGENT['credentials'].encode('ascii'),
        p2p=sirius_sdk.P2PConnection(
            my_keys=(
                AGENT['my_verkey'],
                AGENT['my_secret_key']
            ),
            their_verkey=AGENT['agent_verkey']
        )
    )


PARTICIPANTS_META = {
    'SjQbvdunyyxYYismGKsKgg': {
        'label': 'ADI Smart',
        'logo': 'ady_container.png',
        'icon': 'ady_smart.jpg',
        'url': 'https://adi.blockchain-innovation.ch',
        'verkey': 'F2QvfetYxCTRAkLoJp53ys39rAXFDxmZCpUMteadwsGE',
        'organization': 'Azerbaijan Railways'
    },
    'UEUBPiqZwSDS68P47UnCUF': {
        'label': 'DKR',
        'logo': 'ktz_express.svg',
        'icon': 'dkr.png',
        'url': 'https://asu-dkr.blockchain-innovation.ch',
        'verkey': 'Fqs7kY3pMExvVbkJWWhxsPLqLyKRN5hQtXUmtyH5NVEL',
        'organization': 'KTZ Express'
    },
    '2somaS731MdnA64C9a2n2X': {
        'label': 'GR Logistics & Terminals',
        'logo': 'gr_logistics.png',
        'icon': 'gr.jpg',
        'url': 'https://poti.blockchain-innovation.ch',
        'verkey': '22JaqSLVw1o3u84GQnaJ7S8Nki2nrVwBGSYe1zTejf6t',
        'organization': 'Georgian Railway'
    },
    'Tsc4Xyd1HVVVorrrC2ucxg': {
        'label': 'KAZMORTRANSFLOT',
        'logo': 'kazmortransflot.jpg',
        'icon': 'kazmortransflot.jpg',
        'url': 'https://kazmortransflot.blockchain-innovation.ch',
        'verkey': 'FeVZXbjNiUxV3hgoSrB7SZSkqDYWEmTDEQVuz7ZFh1Ep',
        'organization': 'KAZMORTRANSFLOT'
    },
    'MMT5GUctNbDMst6a63sf8U': {
        'label': 'PMIS - PORT OF BAKU',
        'logo': 'port_of_baku.jpg',
        'icon': 'pmis_port_baku.png',
        'url': 'https://pmis.blockchain-innovation.ch',
        'verkey': 'C6PLZPsH2z9VPjQ1GHG6V6yb3S9iYGUrFKqkny3Pyr1z',
        'organization': 'Port of Baku'
    },
    'PNdMhAz7bTJ95PU3qEdPEC': {
        'label': 'Solvo.tos - PORT AKTAU',
        'logo': 'port_aktau.png',
        'icon': 'solvo.tos.png',
        'url': 'https://solvo-tos.blockchain-innovation.ch',
        'verkey': 'DCFYUBe7S5oijQoTiWtFqfGD2zA579M7tc8aFoQ1QSoj',
        'organization': 'Port Aktau'
    }

}

# PARTICIPANTS = [
#     'SjQbvdunyyxYYismGKsKgg','UEUBPiqZwSDS68P47UnCUF','Tsc4Xyd1HVVVorrrC2ucxg','MMT5GUctNbDMst6a63sf8U','2somaS731MdnA64C9a2n2X','PNdMhAz7bTJ95PU3qEdPEC'
# ]
PARTICIPANTS = [
    'UEUBPiqZwSDS68P47UnCUF', 'PNdMhAz7bTJ95PU3qEdPEC', 'MMT5GUctNbDMst6a63sf8U'
]



ADMIN_USERNAME = os.getenv('ADMIN_USERNAME', None)
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD', None)
REDIS = os.getenv('REDIS', None)


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": os.getenv('AGENT_ENTITY', 'default')
    }
}
INBOX_CACHE_KEY = 'inbox'
LEDGERS_CACHE_KEY = 'ledgers'
PATH_INDEX = os.getenv('PATH_INDEX', '')
if PATH_INDEX.isdigit():
    PATH_INDEX = int(PATH_INDEX)
else:
    PATH_INDEX = None
ENABLE_PARALLEL_TXNS = (os.getenv('ENABLE_PARALLEL_TXNS', 'off') == 'on') or (AGENT['is_sea'] is True)


TMTM_PATH = [
    'UEUBPiqZwSDS68P47UnCUF',  # DKR
    'PNdMhAz7bTJ95PU3qEdPEC',  # Port Aktau
    'MMT5GUctNbDMst6a63sf8U',  # Port Baku
    'SjQbvdunyyxYYismGKsKgg',  # ADI Smart
    '2somaS731MdnA64C9a2n2X',  # GR Logistics
]

TMTM_PATH_TIME = {
    'UEUBPiqZwSDS68P47UnCUF': None,  #
    'PNdMhAz7bTJ95PU3qEdPEC': 5,  # DKR => Port Aktau FOR 5 days
    'MMT5GUctNbDMst6a63sf8U': 3,  # Aktau => Port Baku FOR 1 day
    'SjQbvdunyyxYYismGKsKgg': 1,  # Port Baku => ADI Smart FOR 1 day
    '2somaS731MdnA64C9a2n2X': 2,  # ADI => GR Logistics FOR 2 days
}


SINGLE_MICROLEDGER_PER_ENTITY = os.getenv('SINGLE_MICROLEDGER_PER_ENTITY') in ['on', '1', 'yes']
