version: '2'
services:

  db:
    ports:
      - "5432:5432"

  application:
    environment:
      - DJANGO_SETTINGS_MODULE=settings.develop
      - AGENT_CREDENTIALS
      - AGENT_SERVER_ADDRESS
      - AGENT_ENTITY
      - AGENT_MY_VERKEY
      - AGENT_MY_SECRET_KEY
      - AGENT_VERKEY
    volumes:
      - ./app:/app
      - ./ci:/ci
      - ./samples:/samples
    ports:
      - "8000:8000"
