version: '2'
services:

  db:
    ports:
      - "5432:5432"

  solvo_tos:
    environment:
      - DJANGO_SETTINGS_MODULE=settings.develop
    volumes:
      - ./app/settings:/app/settings
    ports:
      - "8001:8000"

  pmis:
    environment:
      - DJANGO_SETTINGS_MODULE=settings.develop
    volumes:
      - ./app/settings:/app/settings
    ports:
      - "8002:8000"

  application:
    environment:
      - DJANGO_SETTINGS_MODULE=settings.develop
    volumes:
      - ./app:/app
      - ./ci:/ci
      - ./samples:/samples
    ports:
      - "8000:8000"
