version: '2'
services:

  db:
    ports:
      - "5432:5432"

  application:
    environment:
      - DJANGO_SETTINGS_MODULE=settings.develop
    volumes:
      - ./app:/app
      - ./ci:/ci
    ports:
      - "8000:8000"
